== 1.1 Introducción

La transformación digital ha revolucionado la industria de servicios alimentarios a nivel mundial. Los restaurantes enfrentan la creciente demanda de ofrecer experiencias de servicio eficientes, personalizadas y tecnológicamente avanzadas. En el contexto boliviano, particularmente en ciudades como El Alto, esta transformación representa tanto un desafío como una oportunidad para establecimientos que buscan modernizar sus operaciones y mejorar la experiencia del cliente (Laudon & Laudon, 2012).

El presente proyecto desarrolla un Sistema Integral de Gestión para el Restaurante Bambú que incorpora tecnologías emergentes de inteligencia artificial para optimizar dos procesos fundamentales: la gestión de reservaciones y el punto de venta presencial. A diferencia de soluciones tradicionales que operan de manera aislada, este sistema integra funcionalidades inteligentes que permiten ofrecer un servicio más eficiente y personalizado.

La innovación principal del sistema radica en la implementación de cuatro funcionalidades de inteligencia artificial: un chatbot con capacidad de búsqueda semántica que comprende consultas en lenguaje natural sobre el menú y disponibilidad; un sistema de recomendación de platillos basado en preferencias e historial del cliente; predicción de demanda por día y hora para optimizar la gestión de recursos humanos y de inventario; y análisis de sentimiento sobre las reseñas de clientes para identificar áreas de mejora continua.

El sistema está diseñado específicamente para el contexto boliviano, integrando la pasarela de pagos Red Enlace CyberSource que permite procesar pagos con tarjeta de débito y crédito, así como códigos QR, cumpliendo con las regulaciones de la Autoridad de Supervisión del Sistema Financiero (ASFI) y facilitando la liquidación directa en cuentas bancarias locales.
